### ISSUE TITLE
[feat] Search members in channel

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#124]
## 📢 Description

채널 정보에서 멤버를 눌렀을 때 보여지는 멤버 목록입니다.
멤버 탭은 전체 멤버수가 노출되어 있습니다.
상단에 검색으로 들어와 있는 멤버를 볼 수 있습니다.

## 💎 Requirements

채널에 1명이라도 있어야 유지되기 때문에 멤버 목록이 비어있는 경우는 없습니다.
나는 닉네임 옆에 "(나)" 라고 표시됩니다.
소유주와 관리자는 뱃지로 표시됩니다.
채널에 없는 사용자를 추가할 수 있습니다.

특정 멤버에게 마우스를 올리면  #123 기능이 활성화 됩니다.
점 세개 버튼을 선택하면 사용자에 따라 여러 항목을 합쳐서 보여줍니다.

## ✨ Todo

- [x] 소유주와 관리자는 뱃지로 표시됩니다.
- [x] 나는 닉네임 옆에 "(나)" 라고 표시됩니다.
- [x] 채널에 없는 사용자를 추가할 수 있습니다.
