### ISSUE TITLE
[feat] chat over sockets

### ISSUE THREAD

**Issue by SOONG-E** [42-Jolly-pingpong/front-end#138]
## 📢 Description

실시간 채팅 기능을 소켓을 통해 구현합니다.

## 💎 Requirements

HTTP통신으로 백엔드와 통신하던 방식을 소켓을 통한 방식으로 수정합니다.

## ✨ Todo

- [ ] 소켓을 통해 새로운 메시지를 보낼 수 있습니다.
- [ ] 새로운 메시지가 왔을 때 채널 참가자는 실시간으로 새로운 메시지를 전송받아야합니다.
- [ ] 사용자의 상태를 소켓을 통해 바꾼 후, 채널 참가자는 바뀐 정보를 소켓을 통해 전달받습니다.
- [ ] 사용자의 역할를 소켓을 통해 바꾼 후, 채널 참가자는 바뀐 정보를 소켓을 통해 전달받습니다.
