### ISSUE TITLE
[feat] Convert HTML to Tailwind CSS for ping-pong

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#139]
## 📢 Description

탁구 애니메이션을 구현합니다.
슬랙에 공유한 HTML 소스를 우리 프로젝트에 맞게 변환해야 합니다.

## 💎 Requirements

1280 이하일 때 작은 탁구대, 이상일 때 큰 탁구대가 나오도록 반응형 추가

## ✨ Todo

- [x] HTML 소스 파악
- [x] HTML -> JSX로 변환
- [x] HTML에서 쓰인 CSS 클래스 분석
- [x] CSS 효과 Tailwind로 변경
