### ISSUE TITLE
[refactor] migrate from cra to vite

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#26]
## 📢 Description

요즘 CRA보다 [Vite](https://vitejs.dev/)나 [Parcel](https://parceljs.org/)을 많이 쓰는 추세라고 해요.
그래서 CRA보다 100배 빠른 Vite로 전환할게요~!

그리고 저는 Webpack이 오류를 발생해 아직 프로젝트를 실행해보지 못했습니다... 엉엉

## ✨ Todo

- [x] vite 설치
- [x] 필요 & 불필요한 dependencies 정리
- [x] vite 환경설정 구성
- [x] vite build 테스트
