### ISSUE TITLE
[chore] update github issue templates

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/front-end#44]
## 📢 Description

깃허브 이슈 템플릿 구성에 component를 추가하려고 합니다.
기존 domain -> view -> feat에서 **domain -> view -> component -> feat**로 변경됩니다.

설명도 변경되기 때문에 README와 연관된 이슈 템플릿들도 내용이 업데이트 될 예정입니다.

## ✨ Todo

- [ ] componet.md 추가
- [ ] component.md 내용 정리
- [ ] view와 feat 템플릿 수정
- [ ] README.md 수정
